from django.urls import path

from .reservation_views import (
    ReservationCancelView,
    ReservationConfirmView,
    ReservationConvertView,
    ReservationDetailView,
    ReservationListCreateView,
    ReservationRejectView,
)
from .views import (
    AssignOrderView,
    CancelOrderView,
    CompleteOrderView,
    CreateOrderView,
    EvaluateOrderView,
    FavoriteListView,
    FavoriteToggleView,
    GameCategoryListView,
    GrabOrderView,
    MyEvaluationListView,
    OrderListView,
    OrderQuoteView,
    OrderStatsView,
    RankingView,
    RefundOrderView,
    RejectOrderView,
    ReplyEvaluationView,
    ServiceDetailView,
    ServiceEvaluationListView,
    ServiceListView,
    StartOrderServiceView,
    TipOrderView,
)

urlpatterns = [
    path('game-categories/', GameCategoryListView.as_view()),
    path('services/', ServiceListView.as_view()),
    path('services/<int:service_id>/', ServiceDetailView.as_view()),
    path('services/<int:service_id>/evaluations/', ServiceEvaluationListView.as_view()),
    path('favorites/', FavoriteListView.as_view()),
    path('favorites/toggle/', FavoriteToggleView.as_view()),
    path('rankings/', RankingView.as_view()),
    path('create/', CreateOrderView.as_view()),
    path('quote/', OrderQuoteView.as_view()),
    path('orders/', OrderListView.as_view(), name='order-list'),
    path('orders/<int:order_id>/grab/', GrabOrderView.as_view()),
    path('orders/<int:order_id>/start/', StartOrderServiceView.as_view()),
    path('orders/<int:order_id>/start-service/', StartOrderServiceView.as_view()),
    path('orders/<int:order_id>/complete/', CompleteOrderView.as_view()),
    path('orders/<int:order_id>/tip/', TipOrderView.as_view()),
    path('orders/<int:order_id>/cancel/', CancelOrderView.as_view()),
    path('orders/<int:order_id>/reject/', RejectOrderView.as_view()),
    path('orders/<int:order_id>/refund/', RefundOrderView.as_view()),
    path('orders/<int:order_id>/assign/', AssignOrderView.as_view()),
    # 预约（ORD-1/2）：与订单共用前缀但独立 ID 空间，路径上用 reservations 区分
    path('reservations/', ReservationListCreateView.as_view(), name='reservation-list'),
    path('reservations/<int:reservation_id>/', ReservationDetailView.as_view()),
    path('reservations/<int:reservation_id>/confirm/', ReservationConfirmView.as_view()),
    path('reservations/<int:reservation_id>/reject/', ReservationRejectView.as_view()),
    path('reservations/<int:reservation_id>/cancel/', ReservationCancelView.as_view()),
    path('reservations/<int:reservation_id>/convert/', ReservationConvertView.as_view()),
    path('evaluate/', EvaluateOrderView.as_view()),
    path('evaluations/mine/', MyEvaluationListView.as_view()),
    path('evaluations/<int:evaluation_id>/reply/', ReplyEvaluationView.as_view()),
    path('stats/', OrderStatsView.as_view()),
]
