# Generated by Django 6.0.4 on 2026-06-26 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('expire_at', models.DateTimeField(blank=True, null=True, verbose_name='截止时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('boss_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='老板入口token')),
                ('provider_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='陪玩入口token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audition_links', to=settings.AUTH_USER_MODEL, verbose_name='创建客服')),
            ],
            options={
                'verbose_name': '试音链接',
                'verbose_name_plural': '试音链接',
                'ordering': ['-created_at'],
            },
        ),
    ]
