# Generated by Django 6.0.4 on 2026-06-29 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditionlink',
            name='boss_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audition_boss_links', to=settings.AUTH_USER_MODEL, verbose_name='老板入口绑定用户'),
        ),
        migrations.AddField(
            model_name='auditionlink',
            name='provider_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audition_provider_links', to=settings.AUTH_USER_MODEL, verbose_name='陪玩入口绑定用户'),
        ),
    ]
