# Generated by Django 6.0.4 on 2026-06-29 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0002_auditionlink_boss_user_auditionlink_provider_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditionSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, default='', max_length=100, verbose_name='联系方式')),
                ('game', models.CharField(blank=True, default='', max_length=100, verbose_name='擅长游戏')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], db_index=True, default='PENDING', max_length=20, verbose_name='审核状态')),
                ('audit_remark', models.CharField(blank=True, default='', max_length=255, verbose_name='审核备注')),
                ('audited_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audition_signups', to=settings.AUTH_USER_MODEL, verbose_name='报名人')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_audition_signups', to=settings.AUTH_USER_MODEL, verbose_name='审核客服')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='audition.auditionlink', verbose_name='试音链接')),
            ],
            options={
                'verbose_name': '试音报名',
                'verbose_name_plural': '试音报名',
                'ordering': ['-created_at'],
                'unique_together': {('link', 'applicant')},
            },
        ),
    ]
