# Generated by Django 6.0.7 on 2026-07-28 08:29

import django.db.models.deletion
from django.db import migrations, models


RELATIONS = (
    ('AuditionLink', 'boss_account_id', 'boss_user_id'),
    ('AuditionLink', 'operator_account_id', 'operator_id'),
    ('AuditionLink', 'provider_account_id', 'provider_user_id'),
    ('AuditionSignup', 'applicant_account_id', 'applicant_id'),
    ('AuditionSignup', 'auditor_account_id', 'auditor_id'),
)


def backfill_accounts(apps, schema_editor):
    LegacyAccountMap = apps.get_model('club_accounts', 'LegacyAccountMap')
    database = schema_editor.connection.alias
    mappings = dict(
        LegacyAccountMap.objects.using(database).values_list(
            'legacy_user_id', 'account_id',
        )
    )
    for model_name, account_field, legacy_field in RELATIONS:
        Model = apps.get_model('audition', model_name)
        for legacy_user_id, account_id in mappings.items():
            Model.objects.using(database).filter(
                **{legacy_field: legacy_user_id},
            ).update(**{account_field: account_id})


def clear_accounts(apps, schema_editor):
    database = schema_editor.connection.alias
    for model_name, account_field, _legacy_field in RELATIONS:
        apps.get_model('audition', model_name).objects.using(database).update(
            **{account_field: None}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0003_auditionsignup'),
        ('club_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditionlink',
            name='boss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audition_boss_links', to='club_accounts.clubaccount', verbose_name='老板入口绑定业务账户'),
        ),
        migrations.AddField(
            model_name='auditionlink',
            name='operator_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audition_links', to='club_accounts.clubaccount', verbose_name='创建客服业务账户'),
        ),
        migrations.AddField(
            model_name='auditionlink',
            name='provider_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audition_provider_links', to='club_accounts.clubaccount', verbose_name='陪玩入口绑定业务账户'),
        ),
        migrations.AddField(
            model_name='auditionsignup',
            name='applicant_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audition_signups', to='club_accounts.clubaccount', verbose_name='报名业务账户'),
        ),
        migrations.AddField(
            model_name='auditionsignup',
            name='auditor_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_audition_signups', to='club_accounts.clubaccount', verbose_name='审核客服业务账户'),
        ),
        migrations.RunPython(backfill_accounts, clear_accounts),
    ]
