# Generated by Django 6.0.4 on 2026-06-18 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_rename_orders_orde_order_i_idx_orders_orde_order_i_93aa9f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='券名称')),
                ('discount_type', models.CharField(choices=[('THRESHOLD', '满减'), ('DIRECT', '无门槛')], default='THRESHOLD', max_length=20, verbose_name='类型')),
                ('threshold', models.IntegerField(default=0, verbose_name='使用门槛（分）')),
                ('amount', models.IntegerField(verbose_name='面额（分）')),
                ('valid_to', models.DateTimeField(verbose_name='有效期至')),
                ('total_qty', models.PositiveIntegerField(default=0, verbose_name='发放总量（0为不限）')),
                ('claimed_qty', models.PositiveIntegerField(default=0, verbose_name='已领取数量')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNUSED', '未使用'), ('USED', '已使用'), ('EXPIRED', '已过期')], db_index=True, default='UNUSED', max_length=20, verbose_name='状态')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='coupons.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户优惠券',
                'verbose_name_plural': '用户优惠券',
                'ordering': ['-claimed_at'],
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
