# Generated by Django 6.0.4 on 2026-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.IntegerField(verbose_name='面额（兴安币账务值）'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='threshold',
            field=models.IntegerField(default=0, verbose_name='使用门槛（兴安币账务值）'),
        ),
    ]
