# Generated by Django 6.0.7 on 2026-07-28 08:29

import django.db.models.deletion
from django.db import migrations, models


def backfill_accounts(apps, schema_editor):
    LegacyAccountMap = apps.get_model('club_accounts', 'LegacyAccountMap')
    UserCoupon = apps.get_model('coupons', 'UserCoupon')
    database = schema_editor.connection.alias
    for legacy_user_id, account_id in LegacyAccountMap.objects.using(
        database,
    ).values_list('legacy_user_id', 'account_id'):
        UserCoupon.objects.using(database).filter(user_id=legacy_user_id).update(
            account_id=account_id,
        )


def clear_accounts(apps, schema_editor):
    apps.get_model('coupons', 'UserCoupon').objects.using(
        schema_editor.connection.alias,
    ).update(account_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts', '0001_initial'),
        ('coupons', '0003_rename_seed_coupon_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='club_accounts.clubaccount'),
        ),
        migrations.RunPython(backfill_accounts, clear_accounts),
    ]
