# Generated by Django 6.0.7 on 2026-07-30 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts', '0002_clubaccount_club_account_type_active_idx_and_more'),
        ('coupons', '0004_usercoupon_account'),
        ('orders', '0022_evaluation_customer_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'valid_to', 'sort_order'], name='coupon_claimable_idx'),
        ),
        migrations.AddIndex(
            model_name='usercoupon',
            index=models.Index(fields=['account', 'status', '-claimed_at'], name='user_coupon_account_idx'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('threshold__gte', 0)), name='coupon_threshold_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='coupon_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('total_qty', 0), ('claimed_qty__lte', models.F('total_qty')), _connector='OR'), name='coupon_claimed_qty_valid'),
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(condition=models.Q(('discount_type__in', ['THRESHOLD', 'DIRECT'])), name='coupon_discount_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='usercoupon',
            constraint=models.UniqueConstraint(fields=('account', 'coupon'), name='uniq_account_coupon'),
        ),
        migrations.AddConstraint(
            model_name='usercoupon',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['UNUSED', 'USED', 'EXPIRED'])), name='user_coupon_status_valid'),
        ),
    ]
