# Generated by Django 6.0.4 on 2026-06-26 06:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_order_boss_discount_order_coupon_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动名称')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('discount_rate', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='活动折扣率(%)')),
                ('commission_rate', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='覆盖抽成率(%)')),
                ('scope', models.CharField(choices=[('ALL', '全场'), ('CATEGORY', '指定分类'), ('ITEMS', '指定商品')], db_index=True, default='ALL', max_length=16, verbose_name='适用范围')),
                ('category', models.CharField(blank=True, default='', max_length=16, verbose_name='适用分类')),
                ('start_at', models.DateTimeField(verbose_name='开始时间')),
                ('end_at', models.DateTimeField(verbose_name='结束时间')),
                ('priority', models.IntegerField(db_index=True, default=0, verbose_name='优先级')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('items', models.ManyToManyField(blank=True, related_name='promotions', to='orders.serviceitem', verbose_name='指定商品')),
            ],
            options={
                'verbose_name': '促销活动',
                'verbose_name_plural': '促销活动',
                'ordering': ['-priority', '-start_at', 'id'],
            },
        ),
    ]
