# Generated by Django 6.0.4 on 2026-06-18 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_created_at_customuser_is_openid_bound_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(db_index=True)),
                ('seq_in_month', models.PositiveIntegerField()),
                ('reward_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Checkin Record',
                'verbose_name_plural': 'Checkin Records',
                'ordering': ['-checkin_date'],
                'unique_together': {('user', 'checkin_date')},
            },
        ),
    ]
