# Generated by Django 6.0.4 on 2026-06-18 07:45

from django.db import migrations

SEED_ACHIEVEMENTS = [
    {'code': 'first_order', 'title': '初出茅庐', 'desc': '完成首单', 'icon': '🎯', 'metric': 'orders', 'target': 1, 'sort_order': 1},
    {'code': 'regular', 'title': '常客', 'desc': '完成 5 单', 'icon': '🔥', 'metric': 'orders', 'target': 5, 'sort_order': 2},
    {'code': 'veteran', 'title': '资深玩家', 'desc': '完成 10 单', 'icon': '🏆', 'metric': 'orders', 'target': 10, 'sort_order': 3},
    {'code': 'big_spender', 'title': '消费达人', 'desc': '累计消费 ¥1000', 'icon': '💎', 'metric': 'amount', 'target': 100000, 'sort_order': 4},
    {'code': 'whale', 'title': '俱乐部之星', 'desc': '累计消费 ¥5000', 'icon': '👑', 'metric': 'amount', 'target': 500000, 'sort_order': 5},
]


def seed(apps, schema_editor):
    Achievement = apps.get_model('users', 'Achievement')
    for item in SEED_ACHIEVEMENTS:
        Achievement.objects.update_or_create(code=item['code'], defaults=item)


def unseed(apps, schema_editor):
    Achievement = apps.get_model('users', 'Achievement')
    codes = [item['code'] for item in SEED_ACHIEVEMENTS]
    Achievement.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_achievement'),
    ]

    operations = [
        migrations.RunPython(seed, unseed),
    ]
