# Generated by Django 6.0.4 on 2026-06-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seed_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='escortprofile',
            name='deposit_paid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escortprofile',
            name='deposit_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escortprofile',
            name='escort_no',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='escortprofile',
            name='total_penalty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='escortprofile',
            name='total_reward',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
