# Generated by Django 6.0.4 on 2026-06-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bosstype_customuser_boss_no_customuser_can_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escortprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', '男陪'), ('FEMALE', '女陪'), ('UNKNOWN', '未知')], db_index=True, default='UNKNOWN', max_length=10),
        ),
    ]
