# Generated by Django 6.0.4 on 2026-06-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_escortlevel_escortprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='game_nickname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='game_region',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='game_uid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
