# Generated by Django 6.0.4 on 2026-07-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_backfill_user_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='escortprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='escorts/avatars/'),
        ),
        migrations.AddField(
            model_name='escortprofile',
            name='cheat_proof',
            field=models.ImageField(blank=True, null=True, upload_to='escorts/cheat_proofs/'),
        ),
        migrations.AddField(
            model_name='escortprofile',
            name='intro_video',
            field=models.FileField(blank=True, null=True, upload_to='escorts/videos/'),
        ),
    ]
