# Generated by Django 6.0.4 on 2026-07-08 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_escortprofile_avatar_escortprofile_cheat_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='customers/avatars/'),
        ),
    ]
