# Generated by Django 6.0.4 on 2026-07-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_provider_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='metric',
            field=models.CharField(choices=[('orders', '完成订单数'), ('amount', '累计消费（兴安币）')], default='orders', max_length=16),
        ),
    ]
