# Generated by Django 6.0.4 on 2026-07-13 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_checkin_config(apps, schema_editor):
    Rule = apps.get_model('users', 'CheckinRuleConfig')
    Gift = apps.get_model('users', 'CheckinGift')
    Rule.objects.get_or_create(
        pk=1,
        defaults={
            'daily_spend_required': 1880,
            'makeup_card_spend_required': 3880,
            'max_makeup_cards': 3,
            'full_attendance_reward_name': 'KOOK专属Tag',
            'full_attendance_reward_desc': '当月完成全部签到后自动获得 KOOK 专属身份 Tag',
            'full_attendance_tag_code': 'XA-MONTH-FULL',
        },
    )
    rewards = [10, 20, 30, 40, 50, 60, 200]
    for day in range(1, 32):
        amount = rewards[(day - 1) % len(rewards)]
        is_week = day % 7 == 0
        Gift.objects.get_or_create(
            checkin_day=day,
            defaults={
                'name': '周签到惊喜礼' if is_week else f'第{day}天签到礼物',
                'description': '连续参与签到的每周惊喜奖励' if is_week else '完成当日签到即可获得',
                'icon': '🎉' if is_week else '🎁',
                'reward_amount': amount,
                'is_active': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_achievement_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckinGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_day', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('icon', models.CharField(blank=True, default='🎁', max_length=20)),
                ('reward_amount', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['checkin_day'],
            },
        ),
        migrations.CreateModel(
            name='CheckinRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_spend_required', models.PositiveIntegerField(default=1880)),
                ('makeup_card_spend_required', models.PositiveIntegerField(default=3880)),
                ('max_makeup_cards', models.PositiveSmallIntegerField(default=3)),
                ('full_attendance_reward_name', models.CharField(default='KOOK专属Tag', max_length=100)),
                ('full_attendance_reward_desc', models.CharField(blank=True, default='当月完成全部签到后自动获得', max_length=255)),
                ('full_attendance_tag_code', models.CharField(default='XA-MONTH-FULL', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checkin Rule Config',
                'verbose_name_plural': 'Checkin Rule Config',
            },
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='gift_icon',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='gift_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='is_makeup',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CheckinMonthProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('makeup_cards', models.PositiveSmallIntegerField(default=0)),
                ('card_grant_days', models.JSONField(blank=True, default=list)),
                ('full_attendance_awarded', models.BooleanField(default=False)),
                ('full_attendance_reward_name', models.CharField(blank=True, default='', max_length=100)),
                ('full_attendance_tag_code', models.CharField(blank=True, default='', max_length=100)),
                ('full_attendance_awarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_month_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', '-updated_at'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
        migrations.RunPython(seed_checkin_config, migrations.RunPython.noop),
    ]
