# Generated by Django 6.0.7 on 2026-07-28 08:27

import django.db.models.deletion
from django.db import migrations, models


RELATIONS = (
    ('CheckinMonthProgress', 'user_id'),
    ('CheckinRecord', 'user_id'),
    ('CustomerGameProfile', 'user_id'),
    ('EscortProfile', 'user_id'),
    ('EscortSchedule', 'provider_id'),
    ('ProviderPassPurchase', 'provider_id'),
)


def backfill_accounts(apps, schema_editor):
    LegacyAccountMap = apps.get_model('club_accounts', 'LegacyAccountMap')
    database = schema_editor.connection.alias
    mappings = dict(
        LegacyAccountMap.objects.using(database).values_list(
            'legacy_user_id', 'account_id',
        )
    )
    for model_name, legacy_field in RELATIONS:
        Model = apps.get_model('users', model_name)
        for legacy_user_id, account_id in mappings.items():
            Model.objects.using(database).filter(
                **{legacy_field: legacy_user_id},
            ).update(account_id=account_id)


def clear_accounts(apps, schema_editor):
    database = schema_editor.connection.alias
    for model_name, _legacy_field in RELATIONS:
        apps.get_model('users', model_name).objects.using(database).update(
            account_id=None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts', '0001_initial'),
        ('users', '0024_bosstype_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinmonthprogress',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkin_month_progresses', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkin_records', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='customergameprofile',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_profiles', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='escortprofile',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escort_profile', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='escortschedule',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='providerpasspurchase',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pass_purchases', to='club_accounts.clubaccount'),
        ),
        migrations.RunPython(backfill_accounts, clear_accounts),
    ]
