# Generated by Django 6.0.7 on 2026-07-30 03:51

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('club_accounts', '0002_clubaccount_club_account_type_active_idx_and_more'),
        ('orders', '0022_evaluation_customer_account_and_more'),
        ('users', '0025_checkinmonthprogress_account_checkinrecord_account_and_more'),
        ('wallet', '0018_disposerecord_dispose_account_type_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='boss_no',
            field=models.CharField(blank=True, default='', max_length=32, unique=True),
        ),
        migrations.AddIndex(
            model_name='checkinrecord',
            index=models.Index(fields=['account', '-checkin_date'], name='checkin_account_date_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'can_login', 'is_active'], name='custom_user_login_idx'),
        ),
        migrations.AddIndex(
            model_name='escortschedule',
            index=models.Index(fields=['account', 'weekday', 'start_minute', 'end_minute'], name='schedule_account_slot_idx'),
        ),
        migrations.AddIndex(
            model_name='providerpasspurchase',
            index=models.Index(fields=['account', '-created_at'], name='pass_purchase_account_idx'),
        ),
        migrations.AddConstraint(
            model_name='bosstype',
            constraint=models.CheckConstraint(condition=models.Q(('discount_rate__range', (1, 100))), name='boss_type_discount_valid'),
        ),
        migrations.AddConstraint(
            model_name='checkingift',
            constraint=models.CheckConstraint(condition=models.Q(('checkin_day__range', (1, 31))), name='checkin_gift_day_valid'),
        ),
        migrations.AddConstraint(
            model_name='checkinmonthprogress',
            constraint=models.UniqueConstraint(fields=('account', 'year', 'month'), name='uniq_account_checkin_month'),
        ),
        migrations.AddConstraint(
            model_name='checkinmonthprogress',
            constraint=models.CheckConstraint(condition=models.Q(('year__gte', 2000)), name='checkin_month_year_valid'),
        ),
        migrations.AddConstraint(
            model_name='checkinmonthprogress',
            constraint=models.CheckConstraint(condition=models.Q(('month__range', (1, 12))), name='checkin_month_value_valid'),
        ),
        migrations.AddConstraint(
            model_name='checkinrecord',
            constraint=models.UniqueConstraint(fields=('account', 'checkin_date'), name='uniq_account_checkin_date'),
        ),
        migrations.AddConstraint(
            model_name='checkinrecord',
            constraint=models.CheckConstraint(condition=models.Q(('seq_in_month__range', (1, 31))), name='checkin_sequence_valid'),
        ),
        migrations.AddConstraint(
            model_name='customergameprofile',
            constraint=models.UniqueConstraint(fields=('account', 'game_category'), name='uniq_account_game_profile'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['CUSTOMER', 'PROVIDER', 'OPERATOR', 'ADMIN'])), name='custom_user_role_valid'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('inviter_commission_rate__range', (0, 100))), name='custom_user_inviter_rate_valid'),
        ),
        migrations.AddConstraint(
            model_name='escortlevel',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate__range', (0, 100))), name='escort_level_rate_valid'),
        ),
        migrations.AddConstraint(
            model_name='escortprofile',
            constraint=models.CheckConstraint(condition=models.Q(('win_rate__range', (0, 100))), name='escort_profile_win_rate_valid'),
        ),
        migrations.AddConstraint(
            model_name='escortprofile',
            constraint=models.CheckConstraint(condition=models.Q(('rating_avg__range', (0, 5))), name='escort_profile_rating_valid'),
        ),
        migrations.AddConstraint(
            model_name='escortprofile',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['AVAILABLE', 'BUSY', 'OFFLINE'])), name='escort_profile_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='escortprofile',
            constraint=models.CheckConstraint(condition=models.Q(('pass_tier', ''), ('pass_tier__in', ['BLACK', 'GOLD', 'SILVER', 'BRONZE']), _connector='OR'), name='escort_profile_pass_tier_valid'),
        ),
        migrations.AddConstraint(
            model_name='escortschedule',
            constraint=models.UniqueConstraint(fields=('account', 'weekday', 'start_minute', 'end_minute'), name='uniq_account_schedule_slot'),
        ),
        migrations.AddConstraint(
            model_name='escortschedule',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__range', (0, 6))), name='escort_schedule_weekday_valid'),
        ),
        migrations.AddConstraint(
            model_name='escortschedule',
            constraint=models.CheckConstraint(condition=models.Q(('start_minute__gte', 0), ('end_minute__lte', 1440), ('start_minute__lt', models.F('end_minute'))), name='escort_schedule_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerpasspurchase',
            constraint=models.CheckConstraint(condition=models.Q(('days__gte', 1)), name='pass_purchase_days_positive'),
        ),
        migrations.AddConstraint(
            model_name='providerpasspurchase',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('starts_at'))), name='pass_purchase_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerpasspurchase',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__lte', models.F('original_amount'))), name='pass_purchase_discount_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerpasspurchase',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount', django.db.models.expressions.CombinedExpression(models.F('original_amount'), '-', models.F('discount_amount')))), name='pass_purchase_amount_valid'),
        ),
    ]
