# Generated by Django 6.0.4 on 2026-06-22 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='角色标识')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='描述')),
                ('permissions', models.JSONField(blank=True, default=list, verbose_name='权限点')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '后台角色',
                'verbose_name_plural': '后台角色',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdminMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_membership', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='console.adminrole', verbose_name='角色')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
                'ordering': ['-created_at'],
            },
        ),
    ]
