# Generated by Django 6.0.4 on 2026-06-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmembership',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='备注'),
        ),
    ]
