# Generated by Django 6.0.7 on 2026-07-28 08:25

import django.db.models.deletion
from django.db import migrations, models


def backfill_account_relations(apps, schema_editor):
    LegacyAccountMap = apps.get_model('club_accounts', 'LegacyAccountMap')
    AdminMembership = apps.get_model('console', 'AdminMembership')
    AdminAuditLog = apps.get_model('console', 'AdminAuditLog')
    database = schema_editor.connection.alias
    mappings = dict(
        LegacyAccountMap.objects.using(database).values_list(
            'legacy_user_id', 'account_id',
        )
    )
    for membership in AdminMembership.objects.using(database).all():
        account_id = mappings.get(membership.user_id)
        if account_id:
            membership.account_id = account_id
            membership.save(update_fields=['account'], using=database)
    for log in AdminAuditLog.objects.using(database).exclude(operator_id=None):
        account_id = mappings.get(log.operator_id)
        if account_id:
            log.operator_account_id = account_id
            log.save(update_fields=['operator_account'], using=database)


def clear_account_relations(apps, schema_editor):
    AdminMembership = apps.get_model('console', 'AdminMembership')
    AdminAuditLog = apps.get_model('console', 'AdminAuditLog')
    database = schema_editor.connection.alias
    AdminMembership.objects.using(database).update(account_id=None)
    AdminAuditLog.objects.using(database).update(operator_account_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts', '0001_initial'),
        ('console', '0004_multi_role_and_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditlog',
            name='operator_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='club_accounts.clubaccount', verbose_name='业务操作人'),
        ),
        migrations.AddField(
            model_name='adminmembership',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_membership', to='club_accounts.clubaccount', verbose_name='业务账户'),
        ),
        migrations.RunPython(
            backfill_account_relations,
            clear_account_relations,
        ),
    ]
