# Generated by Django 6.0.7 on 2026-08-05 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts', '0002_clubaccount_club_account_type_active_idx_and_more'),
        ('console', '0005_adminauditlog_operator_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='封禁原因')),
                ('scope', models.CharField(choices=[('FULL', '全量封禁（锁定 is_active/can_login/can_view）')], default='FULL', max_length=10, verbose_name='封禁范围')),
                ('status', models.CharField(choices=[('ACTIVE', '封禁中'), ('LIFTED', '已手动解封'), ('EXPIRED', '已到期自动解封')], db_index=True, default='ACTIVE', max_length=10, verbose_name='状态')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='自动解封时间（null=永久）')),
                ('banned_at', models.DateTimeField(auto_now_add=True, verbose_name='封禁时间')),
                ('lifted_at', models.DateTimeField(blank=True, null=True, verbose_name='解封时间')),
                ('lift_reason', models.TextField(blank=True, default='', verbose_name='解封原因')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bans', to='club_accounts.clubaccount', verbose_name='被封禁账户')),
                ('lifted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_bans', to=settings.AUTH_USER_MODEL, verbose_name='解封人')),
                ('lifted_by_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lifted_bans_by_account', to='club_accounts.clubaccount', verbose_name='业务解封人')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bans', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('operator_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bans_by_account', to='club_accounts.clubaccount', verbose_name='业务操作人')),
            ],
            options={
                'verbose_name': '封禁记录',
                'verbose_name_plural': '封禁记录',
                'ordering': ['-banned_at'],
                'indexes': [models.Index(fields=['account', 'status'], name='console_acc_account_778978_idx'), models.Index(fields=['status', 'expires_at'], name='console_acc_status_8cd22c_idx')],
            },
        ),
    ]
