# Generated by Django 6.0.7 on 2026-08-05 13:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts', '0002_clubaccount_club_account_type_active_idx_and_more'),
        ('console', '0006_accountban'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountban',
            name='pre_ban_state',
            field=models.JSONField(blank=True, default=dict, help_text='封禁前 ClubAccount 相关布尔开关的取值，形如 {"is_active": true, "can_login": false}。解封时据此回滚，避免把「本来就被停用的账户」误恢复成正常账户。空 dict 视为全 True。', verbose_name='封禁前开关快照'),
        ),
        migrations.AddConstraint(
            model_name='accountban',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('account',), name='uniq_active_ban_per_account'),
        ),
    ]
