# Generated by Django 6.0.5 on 2026-06-24 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message', models.CharField(blank=True, default='', max_length=255, verbose_name='最新消息预览')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='最新消息时间')),
                ('unread_user', models.PositiveIntegerField(default=0, verbose_name='用户未读数')),
                ('unread_support', models.PositiveIntegerField(default=0, verbose_name='客服未读数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_session', to=settings.AUTH_USER_MODEL, verbose_name='发起用户')),
            ],
            options={
                'verbose_name': '客服会话',
                'verbose_name_plural': '客服会话',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_support', models.BooleanField(db_index=True, default=False, verbose_name='是否客服发出')),
                ('content_type', models.CharField(choices=[('TEXT', '文本'), ('IMAGE', '图片')], default='TEXT', max_length=10, verbose_name='内容类型')),
                ('content', models.CharField(blank=True, default='', max_length=1000, verbose_name='文本内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/', verbose_name='图片')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '客服消息',
                'verbose_name_plural': '客服消息',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='chat_chatme_session_70d41b_idx')],
            },
        ),
    ]
