# Generated by Django 6.0.7 on 2026-07-28 08:29

import django.db.models.deletion
from django.db import migrations, models


def backfill_accounts(apps, schema_editor):
    LegacyAccountMap = apps.get_model('club_accounts', 'LegacyAccountMap')
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    ChatSession = apps.get_model('chat', 'ChatSession')
    database = schema_editor.connection.alias
    mappings = dict(
        LegacyAccountMap.objects.using(database).values_list(
            'legacy_user_id', 'account_id',
        )
    )
    for legacy_user_id, account_id in mappings.items():
        ChatSession.objects.using(database).filter(user_id=legacy_user_id).update(
            account_id=account_id,
        )
        ChatMessage.objects.using(database).filter(sender_id=legacy_user_id).update(
            sender_account_id=account_id,
        )


def clear_accounts(apps, schema_editor):
    database = schema_editor.connection.alias
    apps.get_model('chat', 'ChatSession').objects.using(database).update(account_id=None)
    apps.get_model('chat', 'ChatMessage').objects.using(database).update(sender_account_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('club_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_chat_messages', to='club_accounts.clubaccount', verbose_name='发送业务账户'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_session', to='club_accounts.clubaccount', verbose_name='发起业务账户'),
        ),
        migrations.RunPython(backfill_accounts, clear_accounts),
    ]
