# Generated by Django 6.0.7 on 2026-07-30 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_sender_account_chatsession_account'),
        ('club_accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'is_from_support', 'is_read'], name='chat_message_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['account', '-last_message_at'], name='chat_session_account_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(('content_type__in', ['TEXT', 'IMAGE'])), name='chat_message_content_type_valid'),
        ),
    ]
