"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
import sys
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def env_bool(name, default=False):
    """Read a conventional boolean environment variable safely."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


# Local development remains zero-config, while every deploy-time value can be
# injected by the process environment.  Do not put production credentials back
# into this module.
DEBUG = env_bool('DJANGO_DEBUG', True)
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-xa-local-development-key-change-before-production',
)
ALLOWED_HOSTS = [
    host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',') if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'config.admin_config.SuperuserOnlyAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'club_accounts',
    'users',
    'orders',
    'wallet',
    'support',
    'site_messages',
    'announcements',
    'banners',
    'coupons',
    'chat',
    'audition',
    'promotions',
    'console',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 后台写操作审计：置于认证中间件之后，确保 request.user 已就绪。
    # 注意 DRF 的 JWT 认证在视图层执行，故此处在响应阶段读取 request.user。
    'console.middleware.AdminAuditMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(os.environ.get('REDIS_HOST', '127.0.0.1'), int(os.environ.get('REDIS_PORT', '6379')))],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE', 'xa_db'),
        'USER': os.environ.get('MYSQL_USER', 'root'),
        'PASSWORD': os.environ.get('MYSQL_PASSWORD', 'xa_dev_password'),
        'HOST': os.environ.get('MYSQL_HOST', '127.0.0.1'),
        'PORT': os.environ.get('MYSQL_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# 对外媒体域名（对象存储 / 独立媒体域名的过渡入口）。
# 留空时由请求 Host 推导绝对 URL，本地开发零配置。
MEDIA_BASE_URL = os.environ.get('DJANGO_MEDIA_BASE_URL', '').strip()

# 履约凭证策略可按部署环境配置；生产默认强制上传，历史客户端过渡期
# 可显式关闭，待全部升级后再开启。
REQUIRE_ORDER_EVIDENCE_IMAGES = env_bool(
    'REQUIRE_ORDER_EVIDENCE_IMAGES',
    True,
)

AUTH_USER_MODEL = 'users.CustomUser'

UNFOLD = {
    'SITE_TITLE': '兴安电竞管理后台',
    'SITE_HEADER': '兴安电竞',
    'SITE_SUBHEADER': 'Django 数据管理',
    'SITE_URL': '/',
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': True,
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'club_accounts.authentication.ClubAccountAuthentication',
    ),
    'EXCEPTION_HANDLER': 'console.exceptions.console_exception_handler',
}

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', DEBUG)
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if origin.strip()
]

# Celery 配置（broker 复用 Redis）
REDIS_HOST = os.environ.get('REDIS_HOST', '127.0.0.1')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', f'redis://{REDIS_HOST}:{REDIS_PORT}/1')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', f'redis://{REDIS_HOST}:{REDIS_PORT}/2')
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = False  # 测试时设为 True 即可同步执行

# Celery beat 定时计划：每分钟兜底扫描超时未接单订单
CELERY_BEAT_SCHEDULE = {
    'check-pending-timeouts': {
        'task': 'orders.tasks.check_pending_timeouts',
        'schedule': 60.0,
    },
}

# 微信小程序登录配置
WECHAT_MINIAPP_APPID = os.environ.get('WECHAT_APPID', '')
WECHAT_MINIAPP_SECRET = os.environ.get('WECHAT_SECRET', '')
# 未配置真实凭证时回退 mock 登录；可用 WECHAT_MOCK_LOGIN 显式覆盖。
WECHAT_MOCK_LOGIN = env_bool(
    'WECHAT_MOCK_LOGIN',
    default=not (WECHAT_MINIAPP_APPID and WECHAT_MINIAPP_SECRET),
)

# 平台默认抽成率（百分比）。报单审核入账时若 SystemConfig 未配置则回落此值。
PLATFORM_COMMISSION_RATE = 20

# 平台系统账户用户名：承载 shop_income（店铺/平台留存）入账的钱包主体。
# 该账户禁止登录，仅作记账归集，由数据迁移创建。
PLATFORM_SYSTEM_USERNAME = os.environ.get('PLATFORM_SYSTEM_USERNAME', '__platform__')

# 试音链接按端拆分，避免陪玩链接被错误地分发到仅支持老板身份的 H5。
# 保留 AUDITION_LINK_BASE_URL 作为旧部署的向后兼容兜底。
_legacy_audition_base_url = os.environ.get('AUDITION_LINK_BASE_URL', 'https://h5.example.com/audition')
# Keep the historical name for integrations that have not yet moved to the
# per-client settings below.
AUDITION_LINK_BASE_URL = _legacy_audition_base_url
AUDITION_BOSS_LINK_BASE_URL = os.environ.get(
    'AUDITION_BOSS_LINK_BASE_URL', _legacy_audition_base_url,
)
AUDITION_PROVIDER_LINK_BASE_URL = os.environ.get(
    'AUDITION_PROVIDER_LINK_BASE_URL', _legacy_audition_base_url,
)

# KOOK 订单派单通知。默认关闭，避免本地/测试环境误发真实频道。
# 机器人需已加入目标服务器，并拥有目标文字频道的发消息权限。
KOOK_ENABLED = env_bool('KOOK_ENABLED', False)
KOOK_API_BASE_URL = os.environ.get('KOOK_API_BASE_URL', 'https://www.kookapp.cn/api/v3').rstrip('/')
KOOK_BOT_TOKEN = os.environ.get('KOOK_BOT_TOKEN', '')
KOOK_DISPATCH_CHANNEL_ID = os.environ.get('KOOK_DISPATCH_CHANNEL_ID', '')
KOOK_DISPATCH_NEW_ORDERS = env_bool('KOOK_DISPATCH_NEW_ORDERS', True)
KOOK_DISPATCH_REJECTED_ORDERS = env_bool('KOOK_DISPATCH_REJECTED_ORDERS', True)
KOOK_DISPATCH_MENTION_ROLE_IDS = tuple(
    value.strip()
    for value in os.environ.get('KOOK_DISPATCH_MENTION_ROLE_IDS', '').split(',')
    if value.strip()
)
KOOK_ADMIN_ORDER_URL = os.environ.get('KOOK_ADMIN_ORDER_URL', '').rstrip('/')
KOOK_REQUEST_TIMEOUT = float(os.environ.get('KOOK_REQUEST_TIMEOUT', '8'))

# 默认最低提现兴安币对应的内部账务值。C 端未配置时回落此值。
MIN_WITHDRAW_AMOUNT = 10000

# ---------------------------------------------------------------------------
# 测试环境覆盖：执行 `manage.py test` 时切换到内存 SQLite 与内存 ChannelLayer，
# 使单元测试无需依赖本地 MySQL / Redis，秒级运行且适配 CI。
# ---------------------------------------------------------------------------
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }
    CHANNEL_LAYERS['default'] = {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
    CELERY_TASK_ALWAYS_EAGER = True
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']
