"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

import os
import sys
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

def env_bool(name, default=False):
    """Read a conventional boolean environment variable safely."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


# Local development remains zero-config, while every deploy-time value can be
# injected by the process environment.  Do not put production credentials back
# into this module.
#
# 安全基线（B1-T1）：本地默认值保持不变（DEBUG=True、通配 Host），但一旦
# DJANGO_DEBUG=False，缺失的生产配置会在本模块末尾的 run_startup_checks() 里
# 直接抛 ImproperlyConfigured，让进程起不来 —— 而不是带着开发密钥裸奔上线。
DEBUG = env_bool('DJANGO_DEBUG', True)
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    # 仅用于本地开发；生产由 run_startup_checks() 强制要求环境变量注入。
    'django-insecure-xa-local-development-key-change-before-production',
)
# 生产不再隐式回落 '*'：未显式配置时留空，由启动校验报错并阻断启动。
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        'DJANGO_ALLOWED_HOSTS', '*' if DEBUG else '',
    ).split(',')
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'unfold',
    'config.admin_config.SuperuserOnlyAdminConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'club_accounts',
    'users',
    'orders',
    'wallet',
    'support',
    'site_messages',
    'announcements',
    'banners',
    'coupons',
    'chat',
    'audition',
    'promotions',
    'console',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 后台写操作审计：置于认证中间件之后，确保 request.user 已就绪。
    # 注意 DRF 的 JWT 认证在视图层执行，故此处在响应阶段读取 request.user。
    'console.middleware.AdminAuditMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [(os.environ.get('REDIS_HOST', '127.0.0.1'), int(os.environ.get('REDIS_PORT', '6379')))],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('MYSQL_DATABASE', 'xa_db'),
        'USER': os.environ.get('MYSQL_USER', 'root'),
        'PASSWORD': os.environ.get('MYSQL_PASSWORD', 'xa_dev_password'),
        'HOST': os.environ.get('MYSQL_HOST', '127.0.0.1'),
        'PORT': os.environ.get('MYSQL_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# 对外媒体域名（对象存储 / 独立媒体域名的过渡入口）。
# 留空时由请求 Host 推导绝对 URL，本地开发零配置。
MEDIA_BASE_URL = os.environ.get('DJANGO_MEDIA_BASE_URL', '').strip()

# 履约凭证策略可按部署环境配置；生产默认强制上传，历史客户端过渡期
# 可显式关闭，待全部升级后再开启。
REQUIRE_ORDER_EVIDENCE_IMAGES = env_bool(
    'REQUIRE_ORDER_EVIDENCE_IMAGES',
    True,
)

# 资金写接口是否强制要求客户端携带 client_request_id。
#
# 默认 False：存量小程序尚未发版，强开会让下单/提现直接不可用。此时后端仍会
# 用「账户+业务+关键参数」派生键做 60 秒窗口去重（见
# wallet.services.claim_fund_write），挡得住弱网重试与连点。
# 各端发版带上 client_request_id 后，把本项置 True，即可升级为永久强幂等。
REQUIRE_CLIENT_REQUEST_ID = env_bool('REQUIRE_CLIENT_REQUEST_ID', False)

AUTH_USER_MODEL = 'users.CustomUser'

UNFOLD = {
    'SITE_TITLE': '兴安电竞管理后台',
    'SITE_HEADER': '兴安电竞',
    'SITE_SUBHEADER': 'Django 数据管理',
    'SITE_URL': '/',
    'SHOW_HISTORY': True,
    'SHOW_VIEW_ON_SITE': True,
}

# 限流档位：作用于声明了 throttle_scope 的视图（ScopedRateThrottle）。
# 未声明 scope 的视图不受影响，因此加默认限流类是零风险的。
THROTTLE_RATE_LOGIN = os.environ.get('THROTTLE_RATE_LOGIN', '10/min')
THROTTLE_RATE_ORDER_WRITE = os.environ.get('THROTTLE_RATE_ORDER_WRITE', '30/min')
THROTTLE_RATE_CHECKIN = os.environ.get('THROTTLE_RATE_CHECKIN', '10/min')
THROTTLE_RATE_WALLET_WRITE = os.environ.get('THROTTLE_RATE_WALLET_WRITE', '10/min')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'club_accounts.authentication.ClubAccountAuthentication',
    ),
    # fail-closed 兜底：任何忘记声明 permission_classes 的新视图都会被这里挡下
    # （既要业务账户已登录，又要具备后台身份），逼开发显式声明放行范围。
    # 需要匿名访问的接口（登录/刷新）必须显式写 permission_classes = [AllowAny]。
    'DEFAULT_PERMISSION_CLASSES': (
        'club_accounts.permissions.IsClubAccountAuthenticated',
        'console.permissions.IsConsoleUser',
    ),
    # 只对写操作计数：读接口（列表/详情）不占配额，详见 common.throttling。
    'DEFAULT_THROTTLE_CLASSES': (
        'common.throttling.WriteScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login': THROTTLE_RATE_LOGIN,
        'order_write': THROTTLE_RATE_ORDER_WRITE,
        'checkin': THROTTLE_RATE_CHECKIN,
        'wallet_write': THROTTLE_RATE_WALLET_WRITE,
    },
    'EXCEPTION_HANDLER': 'console.exceptions.console_exception_handler',
}

# 限流计数依赖缓存。本地零配置走进程内存；多进程部署请通过 DJANGO_CACHE_URL
# 指向 Redis，否则每个 worker 各算各的，限流会被 worker 数量放大。
_CACHE_URL = os.environ.get('DJANGO_CACHE_URL', '').strip()
if _CACHE_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _CACHE_URL,
        },
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'xa-default-cache',
        },
    }

# ---------------------------------------------------------------------------
# 结构化日志：资金链路必须可审计、可检索。
# xa.money 通道恒为 JSON 行，字段见 common.logging_utils.BUSINESS_FIELDS。
# ---------------------------------------------------------------------------
LOG_LEVEL = os.environ.get('DJANGO_LOG_LEVEL', 'INFO').upper()
# 应用日志格式：本地默认人类可读，生产默认 JSON；可用 DJANGO_LOG_FORMAT 覆盖。
LOG_FORMAT = os.environ.get('DJANGO_LOG_FORMAT', 'plain' if DEBUG else 'json').lower()
if LOG_FORMAT not in {'plain', 'json'}:
    LOG_FORMAT = 'json'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'common.logging_utils.JsonLogFormatter',
        },
        'plain': {
            'format': '[%(asctime)s] %(levelname)s %(name)s %(module)s:%(lineno)d %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': LOG_FORMAT,
        },
        # 资金事件恒用 JSON，便于对账脚本直接解析，不随 DEBUG 变化。
        'money': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # 业务日志根：orders / wallet / users 等模块统一挂在 xa.* 下。
        'xa': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'xa.money': {
            'handlers': ['money'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

from datetime import timedelta  # noqa: E402

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

CORS_ALLOW_ALL_ORIGINS = env_bool('CORS_ALLOW_ALL_ORIGINS', DEBUG)
CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if origin.strip()
]

# Celery 配置（broker 复用 Redis）
REDIS_HOST = os.environ.get('REDIS_HOST', '127.0.0.1')
REDIS_PORT = os.environ.get('REDIS_PORT', '6379')
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', f'redis://{REDIS_HOST}:{REDIS_PORT}/1')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', f'redis://{REDIS_HOST}:{REDIS_PORT}/2')
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = False  # 测试时设为 True 即可同步执行

# Celery beat 定时计划：每分钟兜底扫描超时未接单订单
CELERY_BEAT_SCHEDULE = {
    'check-pending-timeouts': {
        'task': 'orders.tasks.check_pending_timeouts',
        'schedule': 60.0,
    },
}

# 微信小程序登录配置
WECHAT_MINIAPP_APPID = os.environ.get('WECHAT_APPID', '')
WECHAT_MINIAPP_SECRET = os.environ.get('WECHAT_SECRET', '')
# 未配置真实凭证时回退 mock 登录；可用 WECHAT_MOCK_LOGIN 显式覆盖。
WECHAT_MOCK_LOGIN = env_bool(
    'WECHAT_MOCK_LOGIN',
    default=not (WECHAT_MINIAPP_APPID and WECHAT_MINIAPP_SECRET),
)

# 平台默认抽成率（百分比）。报单审核入账时若 SystemConfig 未配置则回落此值。
PLATFORM_COMMISSION_RATE = 20

# 平台系统账户用户名：承载 shop_income（店铺/平台留存）入账的钱包主体。
# 该账户禁止登录，仅作记账归集，由数据迁移创建。
PLATFORM_SYSTEM_USERNAME = os.environ.get('PLATFORM_SYSTEM_USERNAME', '__platform__')

# 试音链接按端拆分，避免陪玩链接被错误地分发到仅支持老板身份的 H5。
# 保留 AUDITION_LINK_BASE_URL 作为旧部署的向后兼容兜底。
_legacy_audition_base_url = os.environ.get('AUDITION_LINK_BASE_URL', 'https://h5.example.com/audition')
# Keep the historical name for integrations that have not yet moved to the
# per-client settings below.
AUDITION_LINK_BASE_URL = _legacy_audition_base_url
AUDITION_BOSS_LINK_BASE_URL = os.environ.get(
    'AUDITION_BOSS_LINK_BASE_URL', _legacy_audition_base_url,
)
AUDITION_PROVIDER_LINK_BASE_URL = os.environ.get(
    'AUDITION_PROVIDER_LINK_BASE_URL', _legacy_audition_base_url,
)

# KOOK 订单派单通知。默认关闭，避免本地/测试环境误发真实频道。
# 机器人需已加入目标服务器，并拥有目标文字频道的发消息权限。
KOOK_ENABLED = env_bool('KOOK_ENABLED', False)
KOOK_API_BASE_URL = os.environ.get('KOOK_API_BASE_URL', 'https://www.kookapp.cn/api/v3').rstrip('/')
KOOK_BOT_TOKEN = os.environ.get('KOOK_BOT_TOKEN', '')
KOOK_DISPATCH_CHANNEL_ID = os.environ.get('KOOK_DISPATCH_CHANNEL_ID', '')
KOOK_DISPATCH_NEW_ORDERS = env_bool('KOOK_DISPATCH_NEW_ORDERS', True)
KOOK_DISPATCH_REJECTED_ORDERS = env_bool('KOOK_DISPATCH_REJECTED_ORDERS', True)
KOOK_DISPATCH_MENTION_ROLE_IDS = tuple(
    value.strip()
    for value in os.environ.get('KOOK_DISPATCH_MENTION_ROLE_IDS', '').split(',')
    if value.strip()
)
KOOK_ADMIN_ORDER_URL = os.environ.get('KOOK_ADMIN_ORDER_URL', '').rstrip('/')
KOOK_REQUEST_TIMEOUT = float(os.environ.get('KOOK_REQUEST_TIMEOUT', '8'))

# 默认最低提现兴安币对应的内部账务值。C 端未配置时回落此值。
MIN_WITHDRAW_AMOUNT = 10000

# ---------------------------------------------------------------------------
# 测试环境覆盖：执行 `manage.py test` 时切换到内存 SQLite 与内存 ChannelLayer，
# 使单元测试无需依赖本地 MySQL / Redis，秒级运行且适配 CI。
# ---------------------------------------------------------------------------
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }
    CHANNEL_LAYERS['default'] = {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    }
    CELERY_TASK_ALWAYS_EAGER = True
    PASSWORD_HASHERS = ['django.contrib.auth.hashers.MD5PasswordHasher']


# ---------------------------------------------------------------------------
# 启动期配置自检（必须放在文件最末尾，确保校验的是最终生效值）。
#
# DEBUG=True 时全部跳过 —— 本地开发与 `manage.py test` 保持零配置可跑；
# DEBUG=False 时缺失 SECRET_KEY / ALLOWED_HOSTS 等会直接抛 ImproperlyConfigured，
# 在 `manage.py check` / runserver / gunicorn 启动阶段就失败。
# ---------------------------------------------------------------------------
from config.checks import run_startup_checks  # noqa: E402

run_startup_checks(
    debug=DEBUG,
    secret_key=SECRET_KEY,
    allowed_hosts=ALLOWED_HOSTS,
    cors_allow_all_origins=CORS_ALLOW_ALL_ORIGINS,
    cors_allowed_origins=CORS_ALLOWED_ORIGINS,
    databases=DATABASES,
    wechat_mock_login=WECHAT_MOCK_LOGIN,
)
