# Generated by Django 6.0.4 on 2026-06-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500, verbose_name='图片地址')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='标题')),
                ('link_type', models.CharField(choices=[('NONE', '无跳转'), ('PRODUCT', '商品详情'), ('ANNOUNCEMENT', '公告详情'), ('URL', '外部链接')], default='NONE', max_length=20, verbose_name='跳转类型')),
                ('link_value', models.CharField(blank=True, default='', max_length=255, verbose_name='跳转目标')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '首页轮播',
                'verbose_name_plural': '首页轮播',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
