# Generated by Django 6.0.4 on 2026-06-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_url',
        ),
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(default='', help_text='请上传 750×320 像素的图片', upload_to='banners/', verbose_name='图片'),
            preserve_default=False,
        ),
    ]
