# Generated by Django 6.0.4 on 2026-05-08 06:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, db_index=True, default='', max_length=32, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('game_rounds', models.PositiveIntegerField(default=1)),
                ('customer_phone_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('provider_name_snapshot', models.CharField(blank=True, default='', max_length=50)),
                ('service_name_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('unit_price_snapshot', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('payment_status', models.CharField(choices=[('UNPAID', '未支付'), ('PAID', '已支付'), ('REFUNDED', '已退款')], db_index=True, default='PAID', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', '待接单'), ('GRABBED', '已接单'), ('IN_SERVICE', '服务中'), ('COMPLETED', '已完成')], db_index=True, default='PENDING', max_length=20)),
                ('grabbed_at', models.DateTimeField(blank=True, null=True)),
                ('in_service_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_orders', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_orders', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.serviceitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField(blank=True, default='')),
                ('is_anonymous', models.BooleanField(default=False)),
                ('reply_content', models.TextField(blank=True, default='')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
