# Generated by Django 6.0.4 on 2026-06-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_service_item_extra_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='orderstatuslog',
            new_name='orders_orde_order_i_93aa9f_idx',
            old_name='orders_orde_order_i_idx',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='category',
            field=models.CharField(choices=[('NORMAL', '陪玩服务'), ('GIFT', '礼品套餐')], db_index=True, default='NORMAL', max_length=16),
        ),
    ]
