# Generated by Django 6.0.4 on 2026-06-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_commission_rate_order_inviter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='boss_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='original_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
