# Generated by Django 6.0.4 on 2026-06-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_servicefavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='game_nickname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='game_region',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='game_uid',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
