# Generated by Django 6.0.5 on 2026-07-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_escort_mode_alter_gamecategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprovider',
            name='commission_fixed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderprovider',
            name='commission_type',
            field=models.CharField(choices=[('PERCENT', '百分比抽成'), ('FIXED', '固定金额抽成')], default='PERCENT', max_length=10),
        ),
    ]
