# Generated by Django 6.0.7 on 2026-07-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_kookdispatchrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecategory',
            name='icon',
            field=models.ImageField(blank=True, help_text='游戏图标，建议使用正方形图片；未上传时前端展示默认图标', null=True, upload_to='game_categories/', verbose_name='图标'),
        ),
    ]
