# Generated by Django 6.0.7 on 2026-07-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_serviceitem_required_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatuslog',
            name='action',
            field=models.CharField(choices=[('CREATE', '创建'), ('GRAB', '接单'), ('ASSIGN', '派单'), ('START', '开始服务'), ('COMPLETE', '完成'), ('REJECT', '拒单'), ('CANCEL', '取消'), ('REFUND', '退款'), ('TRANSFER', '转单'), ('AUTO_CANCEL', '超时自动取消')], db_index=True, max_length=20),
        ),
    ]
