# Generated by Django 6.0.7 on 2026-08-03 08:16

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts', '0002_clubaccount_club_account_type_active_idx_and_more'),
        ('orders', '0023_evaluation_evaluation_provider_time_idx_and_more'),
        ('promotions', '0002_promotion_category_fk'),
        ('support', '0002_supportcontactcard_wecom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('provider_income__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('amount'), '-', models.F('inviter_commission')), '-', models.F('shop_income')))), name='order_split_not_exceed_amount'),
        ),
    ]
