# Generated by Django 6.0.7 on 2026-07-28 08:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0024_bosstype_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('account_type', models.CharField(choices=[('STAFF', '后台人员'), ('BOSS', '老板'), ('PROVIDER', '陪玩')], db_index=True, max_length=20)),
                ('openid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='accounts/avatars/')),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, default='', max_length=50)),
                ('real_name', models.CharField(blank=True, default='', max_length=50)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_openid_bound', models.BooleanField(default=False)),
                ('game_region', models.CharField(blank=True, default='', max_length=50)),
                ('game_nickname', models.CharField(blank=True, default='', max_length=50)),
                ('game_uid', models.CharField(blank=True, default='', max_length=50)),
                ('inviter_commission_rate', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('account_no', models.CharField(db_index=True, max_length=32, unique=True)),
                ('can_login', models.BooleanField(db_index=True, default=True)),
                ('can_view', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boss_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_accounts', to='users.bosstype')),
                ('inviter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitees', to='club_accounts.clubaccount')),
            ],
            options={
                'verbose_name': '俱乐部业务账户',
                'verbose_name_plural': '俱乐部业务账户',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LegacyAccountMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_user_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('legacy_role', models.CharField(blank=True, default='', max_length=20)),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='legacy_mapping', to='club_accounts.clubaccount')),
            ],
            options={
                'verbose_name': '旧账户映射',
                'verbose_name_plural': '旧账户映射',
                'ordering': ['legacy_user_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='clubaccount',
            constraint=models.CheckConstraint(condition=models.Q(('account_type__in', ['STAFF', 'BOSS', 'PROVIDER'])), name='club_account_type_valid'),
        ),
    ]
