# Generated by Django 6.0.7 on 2026-07-30 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts', '0001_initial'),
        ('users', '0025_checkinmonthprogress_account_checkinrecord_account_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clubaccount',
            index=models.Index(fields=['account_type', 'is_active', '-created_at'], name='club_account_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='clubaccount',
            index=models.Index(fields=['account_type', 'can_login', 'is_active'], name='club_account_login_idx'),
        ),
        migrations.AddConstraint(
            model_name='clubaccount',
            constraint=models.CheckConstraint(condition=models.Q(('inviter_commission_rate__range', (0, 100))), name='club_account_inviter_rate_valid'),
        ),
    ]
