# Generated by Django 6.0.7 on 2026-07-28 08:29

import django.db.models.deletion
from django.db import migrations, models


def backfill_accounts(apps, schema_editor):
    LegacyAccountMap = apps.get_model('club_accounts', 'LegacyAccountMap')
    Message = apps.get_model('site_messages', 'Message')
    database = schema_editor.connection.alias
    for legacy_user_id, account_id in LegacyAccountMap.objects.using(
        database,
    ).values_list('legacy_user_id', 'account_id'):
        Message.objects.using(database).filter(recipient_id=legacy_user_id).update(
            recipient_account_id=account_id,
        )


def clear_accounts(apps, schema_editor):
    apps.get_model('site_messages', 'Message').objects.using(
        schema_editor.connection.alias,
    ).update(recipient_account_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts', '0001_initial'),
        ('site_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='site_messag_recipie_e3436d_idx',
            old_name='site_messag_recipie_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='club_accounts.clubaccount'),
        ),
        migrations.RunPython(backfill_accounts, clear_accounts),
    ]
