# Generated by Django 6.0.7 on 2026-07-30 03:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts', '0002_clubaccount_club_account_type_active_idx_and_more'),
        ('site_messages', '0002_rename_site_messag_recipie_idx_site_messag_recipie_e3436d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient_account', 'is_read', '-created_at'], name='site_msg_account_unread_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient_account', 'type', '-created_at'], name='site_msg_account_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ['SYSTEM', 'ORDER', 'SUPPORT', 'PROMOTION'])), name='site_message_type_valid'),
        ),
    ]
