# Generated by Django 6.0.4 on 2026-06-24 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SystemConfig',
                'verbose_name_plural': 'SystemConfigs',
            },
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('TOPUP', '充值'), ('PAY', '支付'), ('INCOME', '收益'), ('WITHDRAW', '提现'), ('REWARD', '奖励')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ProviderReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], db_index=True, default='PENDING', max_length=20)),
                ('commission_rate', models.PositiveSmallIntegerField(default=0)),
                ('payout_amount', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('audit_remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audited_at', models.DateTimeField(blank=True, null=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_reports', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_reports', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.transaction')),
            ],
            options={
                'verbose_name': 'ProviderReport',
                'verbose_name_plural': 'ProviderReports',
                'ordering': ['-created_at'],
            },
        ),
    ]
