# Generated by Django 6.0.5 on 2026-06-24 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_systemconfig_alter_transaction_tx_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payee_method', models.CharField(choices=[('WECHAT', '微信'), ('ALIPAY', '支付宝'), ('BANK', '银行卡')], max_length=20)),
                ('payee_account', models.CharField(max_length=100)),
                ('payee_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], db_index=True, default='PENDING', max_length=20)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('audit_remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audited_at', models.DateTimeField(blank=True, null=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WithdrawRequest',
                'verbose_name_plural': 'WithdrawRequests',
                'ordering': ['-created_at'],
            },
        ),
    ]
