# Generated by Django 6.0.4 on 2026-06-25 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_withdrawrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_gift',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_recharge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('TOPUP', '充值'), ('PAY', '支付'), ('INCOME', '收益'), ('WITHDRAW', '提现'), ('REWARD', '奖励'), ('GIFT', '赠送')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('gift_amount', models.PositiveIntegerField(default=0)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.transaction')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_recharges', to=settings.AUTH_USER_MODEL)),
                ('recharge_tx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharge_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RechargeRecord',
                'verbose_name_plural': 'RechargeRecords',
                'ordering': ['-created_at'],
            },
        ),
    ]
