# Generated by Django 6.0.4 on 2026-06-25 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_total_gift_wallet_total_recharge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('TOPUP', '充值'), ('PAY', '支付'), ('INCOME', '收益'), ('WITHDRAW', '提现'), ('REWARD', '奖励'), ('GIFT', '赠送'), ('PENALTY', '罚款')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='DisposeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispose_type', models.CharField(choices=[('REWARD', '奖励'), ('PENALTY', '罚款')], db_index=True, max_length=16)),
                ('amount', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_disposes', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wallet.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispose_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DisposeRecord',
                'verbose_name_plural': 'DisposeRecords',
                'ordering': ['-created_at'],
            },
        ),
    ]
