# Generated by Django 6.0.4 on 2026-06-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_transaction_tx_type_disposerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('TOPUP', '充值'), ('PAY', '支付'), ('INCOME', '收益'), ('WITHDRAW', '提现'), ('REWARD', '奖励'), ('GIFT', '赠送'), ('PENALTY', '罚款'), ('SHOP_INCOME', '平台收入')], db_index=True, max_length=20),
        ),
    ]
