# Generated by Django 6.0.4 on 2026-07-07 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_transaction_tx_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='operator',
            field=models.ForeignKey(blank=True, help_text='后台调账等人工操作的操作人；系统自动流水为空', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
