# Generated by Django 6.0.5 on 2026-07-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_transaction_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechargerecord',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='充值凭证截图（转账/收款截图）', null=True, upload_to='recharges/'),
        ),
        migrations.AddField(
            model_name='rechargerecord',
            name='trade_no',
            field=models.CharField(blank=True, default='', help_text='第三方交易/转账流水号，用于对账溯源', max_length=64),
        ),
    ]
