# Generated by Django 6.0.7 on 2026-07-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_report_unique_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='actual_amount',
            field=models.PositiveIntegerField(default=0, help_text='扣税后实际打款给陪玩的金额（内部账务单位）'),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='tax_amount',
            field=models.PositiveIntegerField(default=0, help_text='按税率计算的税额（内部账务单位）'),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='tax_rate',
            field=models.PositiveIntegerField(default=0, help_text='申请时快照的提现税率（百分比，0-100）'),
        ),
    ]
