# Generated by Django 6.0.7 on 2026-07-28 08:27

import django.db.models.deletion
from django.db import migrations, models


RELATIONS = (
    ('DisposeRecord', 'account_id', 'user_id'),
    ('DisposeRecord', 'operator_account_id', 'operator_id'),
    ('ProviderReport', 'auditor_account_id', 'auditor_id'),
    ('ProviderReport', 'provider_account_id', 'provider_id'),
    ('RechargeRecord', 'account_id', 'user_id'),
    ('RechargeRecord', 'operator_account_id', 'operator_id'),
    ('Transaction', 'operator_account_id', 'operator_id'),
    ('Wallet', 'account_id', 'user_id'),
    ('WithdrawRequest', 'account_id', 'user_id'),
    ('WithdrawRequest', 'auditor_account_id', 'auditor_id'),
)


def backfill_accounts(apps, schema_editor):
    LegacyAccountMap = apps.get_model('club_accounts', 'LegacyAccountMap')
    database = schema_editor.connection.alias
    mappings = dict(
        LegacyAccountMap.objects.using(database).values_list(
            'legacy_user_id', 'account_id',
        )
    )
    for model_name, account_field, legacy_field in RELATIONS:
        Model = apps.get_model('wallet', model_name)
        for legacy_user_id, account_id in mappings.items():
            Model.objects.using(database).filter(
                **{legacy_field: legacy_user_id},
            ).update(**{account_field: account_id})


def clear_accounts(apps, schema_editor):
    database = schema_editor.connection.alias
    for model_name, account_field, _legacy_field in RELATIONS:
        apps.get_model('wallet', model_name).objects.using(database).update(
            **{account_field: None}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts', '0001_initial'),
        ('wallet', '0016_withdrawrequest_actual_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposerecord',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispose_records', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='disposerecord',
            name='operator_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_disposes', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='providerreport',
            name='auditor_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_reports', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='providerreport',
            name='provider_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_reports', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='rechargerecord',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recharge_records', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='rechargerecord',
            name='operator_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_recharges', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='operator_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_transactions', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to='club_accounts.clubaccount'),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='auditor_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_withdrawals', to='club_accounts.clubaccount'),
        ),
        migrations.RunPython(backfill_accounts, clear_accounts),
    ]
