# Generated by Django 6.0.7 on 2026-07-30 03:51

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


def backfill_withdraw_amount_breakdown(apps, schema_editor):
    """Normalize records created before the tax breakdown fields existed."""
    WithdrawRequest = apps.get_model('wallet', 'WithdrawRequest')
    database = schema_editor.connection.alias
    WithdrawRequest.objects.using(database).update(
        actual_amount=models.F('amount') - models.F('tax_amount'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts', '0002_clubaccount_club_account_type_active_idx_and_more'),
        ('orders', '0022_evaluation_customer_account_and_more'),
        ('wallet', '0017_disposerecord_account_disposerecord_operator_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='disposerecord',
            index=models.Index(fields=['account', 'dispose_type', '-created_at'], name='dispose_account_type_idx'),
        ),
        migrations.AddIndex(
            model_name='providerreport',
            index=models.Index(fields=['provider_account', 'status', '-created_at'], name='report_account_status_idx'),
        ),
        migrations.AddIndex(
            model_name='providerreport',
            index=models.Index(fields=['status', '-created_at'], name='report_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='rechargerecord',
            index=models.Index(fields=['account', '-created_at'], name='recharge_account_time_idx'),
        ),
        migrations.AddIndex(
            model_name='rechargerecord',
            index=models.Index(fields=['trade_no'], name='recharge_trade_no_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'status', '-created_at'], name='tx_wallet_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet', 'tx_type', 'status', '-created_at'], name='tx_wallet_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['order', 'tx_type', 'status'], name='tx_order_type_status_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['external_tx_id'], name='tx_external_id_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawrequest',
            index=models.Index(fields=['account', 'status', '-created_at'], name='withdraw_account_status_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawrequest',
            index=models.Index(fields=['status', '-created_at'], name='withdraw_status_time_idx'),
        ),
        migrations.RunPython(
            backfill_withdraw_amount_breakdown,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='disposerecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='dispose_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='disposerecord',
            constraint=models.CheckConstraint(condition=models.Q(('dispose_type__in', ['REWARD', 'PENALTY'])), name='dispose_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerreport',
            constraint=models.UniqueConstraint(fields=('provider_account', 'order'), name='uniq_provider_account_report'),
        ),
        migrations.AddConstraint(
            model_name='providerreport',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='provider_report_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='providerreport',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate__range', (0, 100))), name='provider_report_rate_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerreport',
            constraint=models.CheckConstraint(condition=models.Q(('payout_amount__lte', models.F('amount'))), name='provider_report_payout_valid'),
        ),
        migrations.AddConstraint(
            model_name='providerreport',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['DRAFT', 'PENDING', 'APPROVED', 'REJECTED'])), name='provider_report_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='rechargerecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='recharge_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('tx_type__in', ['TOPUP', 'PAY', 'INCOME', 'WITHDRAW', 'REWARD', 'GIFT', 'PENALTY', 'DEPOSIT', 'SHOP_INCOME', 'REFUND', 'PASS_PURCHASE'])), name='transaction_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'SUCCESS', 'FAILED'])), name='transaction_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='wallet_balance_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('total_recharge__gte', 0)), name='wallet_recharge_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(condition=models.Q(('total_gift__gte', 0)), name='wallet_gift_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='withdrawrequest',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='withdraw_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='withdrawrequest',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__range', (0, 100))), name='withdraw_tax_rate_valid'),
        ),
        migrations.AddConstraint(
            model_name='withdrawrequest',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__lte', models.F('amount'))), name='withdraw_tax_amount_valid'),
        ),
        migrations.AddConstraint(
            model_name='withdrawrequest',
            constraint=models.CheckConstraint(condition=models.Q(('actual_amount', django.db.models.expressions.CombinedExpression(models.F('amount'), '-', models.F('tax_amount')))), name='withdraw_actual_amount_valid'),
        ),
        migrations.AddConstraint(
            model_name='withdrawrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED'])), name='withdraw_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='withdrawrequest',
            constraint=models.CheckConstraint(condition=models.Q(('payee_method__in', ['WECHAT', 'ALIPAY', 'BANK'])), name='withdraw_payee_method_valid'),
        ),
    ]
