# Generated by Django 6.0.7 on 2026-08-03 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_accounts', '0002_clubaccount_club_account_type_active_idx_and_more'),
        ('orders', '0024_order_order_split_not_exceed_amount'),
        ('wallet', '0019_backfill_wallet_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='transaction_type_valid',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('TOPUP', '充值'), ('PAY', '支付'), ('INCOME', '收益'), ('WITHDRAW', '提现'), ('REWARD', '奖励'), ('GIFT', '赠送'), ('PENALTY', '罚款'), ('DEPOSIT', '押金'), ('SHOP_INCOME', '平台收入'), ('REFUND', '订单退款'), ('PASS_PURCHASE', '通行证购买'), ('WITHDRAW_TAX', '提现税费'), ('ADJUST', '后台调账')], db_index=True, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('tx_type__in', ['TOPUP', 'PAY', 'INCOME', 'WITHDRAW', 'REWARD', 'GIFT', 'PENALTY', 'DEPOSIT', 'SHOP_INCOME', 'REFUND', 'PASS_PURCHASE', 'WITHDRAW_TAX', 'ADJUST'])), name='transaction_type_valid'),
        ),
    ]
